# 视频下载配置文件 (YAML格式)
categories:
  凡人修仙传:
    # ./downloads映射为/volume1/media
    output_path: "./downloads/动画/凡人修仙传"
    urls:
      - https://www.bilibili.com/bangumi/play/ep1231559/
    
  灵笼第二季:
    output_path: "./downloads/动画/灵笼/Season\ 02"
    urls:
      # - https://www.bilibili.com/bangumi/play/ep1633649/ #7

